### ISSUE TITLE
muitas condicionais repetidas

### ISSUE THREAD

**Issue by fabiopipek** [FaKL-Code/TwitchBot#1]
seu código esta lotado de condicionais repetidas pelo amor de deus arruma isso está me dando gatilho

arruma por favor tá todo mundo pedindo arruma pelo amor de deus arruma tem gente chorando tem gente passando mal arruma que o povo tá pedindo arruma pelo amor de deus arruma tem criança de colo correndo tudo isso pra arruma tenha empatia por favor arruma

**Comment by FaKL-Code** [comment]
Alterando as condicionais, agora com fundamentos de case sensitivity
